### ISSUE TITLE
Error: Invalid key length

### ISSUE THREAD

**Issue by Mehavoid** [svbnet/diezel#1]
```
npm test

> diezel@1.0.0 test /home/user/source/diezel
> mocha "./test/*.test.js"



  ImageUrl
    #toString
      ✓ generates a URL string from defaults
      ✓ generates a URL string with constructor and toString options
    #forObject
      ✓ generates a URL string for a normal artist
      ✓ generates a URL string for a normal album
      ✓ generates a URL string for a normal playlist
      ✓ generates a URL string for a custom playlist

  MobileClient
    #signInWithEmail
      1) returns false when signing in with incorrect credentials
      2) signs in with correct credentials
    #restoreSession
      3) restores a session from a previous client

  SongAsset
    ::forLegacyUrl
      4) generates a media URL for a song and version
    #getDecryptedStream
      5) downloads and decrypts a media URL


  6 passing (406ms)
  5 failing

  1) MobileClient
       #signInWithEmail
         returns false when signing in with incorrect credentials:
     Error: Invalid key length
      at Cipheriv.createCipherBase (internal/crypto/cipher.js:101:19)
      at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
      at new Cipheriv (internal/crypto/cipher.js:223:22)
      at Object.createCipheriv (crypto.js:115:10)
      at createCipher (lib/clients/mobileclient.js:31:19)
      at KeyBag.get gatewayToken [as gatewayToken] (lib/clients/mobileclient.js:50:16)
      at MobileClient.initializeKeys (lib/clients/mobileclient.js:162:36)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async MobileClient._ensureSid (lib/clients/mobileclient.js:170:13)
      at async MobileClient.signInWithEmail (lib/clients/mobileclient.js:214:9)
      at async Context.<anonymous> (test/mobileclient.test.js:11:28)

  2) MobileClient
       #signInWithEmail
         signs in with correct credentials:
     Error: Invalid key length
      at Cipheriv.createCipherBase (internal/crypto/cipher.js:101:19)
      at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
      at new Cipheriv (internal/crypto/cipher.js:223:22)
      at Object.createCipheriv (crypto.js:115:10)
      at createCipher (lib/clients/mobileclient.js:31:19)
      at KeyBag.get gatewayToken [as gatewayToken] (lib/clients/mobileclient.js:50:16)
      at MobileClient.initializeKeys (lib/clients/mobileclient.js:162:36)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async MobileClient._ensureSid (lib/clients/mobileclient.js:170:13)
      at async MobileClient.signInWithEmail (lib/clients/mobileclient.js:214:9)
      at async Context.<anonymous> (test/mobileclient.test.js:16:13)

  3) MobileClient
       #restoreSession
         restores a session from a previous client:
     StateError: Not signed in!
      at MobileClient.restoreSession (lib/clients/mobileclient.js:237:19)
      at Context.<anonymous> (test/mobileclient.test.js:24:26)
      at processImmediate (internal/timers.js:439:21)

  4) SongAsset
       ::forLegacyUrl
         generates a media URL for a song and version:
     TypeError: Cannot read property '0' of undefined
      at Function.forLegacyStream (lib/content/SongAsset.js:113:51)
      at Context.<anonymous> (test/SongAsset.test.js:16:46)
      at processImmediate (internal/timers.js:439:21)

  5) SongAsset
       #getDecryptedStream
         downloads and decrypts a media URL:
     TypeError: Cannot read property '0' of undefined
      at Function.forLegacyStream (lib/content/SongAsset.js:113:51)
      at Context.<anonymous> (test/SongAsset.test.js:25:46)
      at processImmediate (internal/timers.js:439:21)


```
the keys I've used https://is.gd/hxZQax

**Comment by svbnet** [comment]
Email me joe@svbnet.co, your GW key is wrong
