### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by 89z** [svbnet/diezel#8]
Using this code:

~~~js
const diezel = require('diezel');

diezel.setKeys({
   MOBILE_API_KEY: process.env.MOBILE_API_KEY,
   MOBILE_GW_KEY: process.env.MOBILE_GW_KEY
});

const { MobileClient } = diezel.clients;
const mobileClient = new MobileClient();

async function main() {
   await mobileClient.signInWithEmail('srpen6@gmail.com', process.env.PASSWORD);
   const album = await mobileClient.getAlbum(7476543);
   mobileClient.mediaClient.getMediaStreamInfo(album.SONGS.data[0], 'MP3_128');
}

main();
~~~

I get this result:

~~~
C:\diezel\node_modules\axios\lib\core\createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 400
    at createError (C:\diezel\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\diezel\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\diezel\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  config: {
    url: 'https://media.deezer.com/v1/get_url',
    method: 'post',
    data: '{"track_tokens":["AAAAAWBQM7VgUUz1NquDH1wPUNvXAkFKiZTGreZN58FF3LsMkHzuNAiKM2RuKLnouem48KBnQYwPFqRAG0Q-zV-UyjGxShetketBb5F31c6H1xfQ00QoZSIWstdUI7w_MZ3-XKRRZowGpA4ExzTZ"],"media":{"type":"FULL","formats":[{"cipher":"BF_CBC_STRIPE","format":"MP3_128"}]}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 251
    },
~~~

**Comment by 89z** [comment]
Looks like the problem is here:

https://github.com/svbnet/diezel/blob/5b6bd8b9c083abcf821736f47a7fd9ba7c92260d/lib/clients/media-client.js#L22

should be just:

~~~js
license_token: this._playerTokenInfo;
~~~

**Comment by svbnet** [comment]
Yeah I haven't tested that part extensively. I might fix it if I get time.
